spring.application.name=ProductService

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_product?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Varun@1916

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port= 8082

spring.servlet.multipart.enabled=true

cloudinary.cloud-name=nor13yji
cloudinary.api-key=443965944621575
cloudinary.api-secret=gjnGbXqa9S8YOnX-lDOONbYFBxk

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.password=hzwf wsuc jeys gmlq
spring.mail.username=varunnrvarunnr60@gmail.com

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
